// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'ILogos:ionicIcon': typeof import('~icons/logos/ionic-icon')['default']
    'ILogos:vitejs': typeof import('~icons/logos/vitejs')['default']
    'ILogos:vue': typeof import('~icons/logos/vue')['default']
    IonApp: typeof import('@ionic/vue')['IonApp']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonNavbar: typeof import('@ionic/vue')['IonNavbar']
    IonNavBar: typeof import('@ionic/vue')['IonNavBar']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
  }
}

export { }
