// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Chart: typeof import('./src/components/Chart.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    'ICarbon:currency': typeof import('~icons/carbon/currency')['default']
    'ICarbon:login': typeof import('~icons/carbon/login')['default']
    'ICarbon:money': typeof import('~icons/carbon/money')['default']
    'IIon:menu': typeof import('~icons/ion/menu')['default']
    'ILogos:ionicIcon': typeof import('~icons/logos/ionic-icon')['default']
    'ILogos:vitejs': typeof import('~icons/logos/vitejs')['default']
    'ILogos:vue': typeof import('~icons/logos/vue')['default']
    IonApp: typeof import('@ionic/vue')['IonApp']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonCard: typeof import('@ionic/vue')['IonCard']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonFooter: typeof import('@ionic/vue')['IonFooter']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonMenu: typeof import('@ionic/vue')['IonMenu']
    IonMenuButton: typeof import('@ionic/vue')['IonMenuButton']
    IonMenuToggle: typeof import('@ionic/vue')['IonMenuToggle']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonSplitPane: typeof import('@ionic/vue')['IonSplitPane']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
  }
}

export { }
